image: wangqipeng/wecloud_train:v0.3.0


setup: |
  uname -a
  echo "hello world"
  python3 --version
  pip3 install -r requirements.txt
  python download_dataset.py

run: |
  python
  -u
  train.py
  --net
  googlenet
  --gpu

profile: |
  python -u train.py --net googlenet --gpu --profiling
